
package com.icp.sigipro.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCR", targetNamespace = "https://fundacionucr.ac.cr/", wsdlLocation = "http://mse.fundacionucr.org/WebServices/Facturar.asmx?wsdl")
public class MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCR
    extends Service
{

    private final static URL MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_WSDL_LOCATION;
    private final static WebServiceException MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_EXCEPTION;
    private final static QName MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_QNAME = new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCR");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://mse.fundacionucr.org/WebServices/Facturar.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_WSDL_LOCATION = url;
        MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_EXCEPTION = e;
    }

    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCR() {
        super(__getWsdlLocation(), MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_QNAME);
    }

    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCR(WebServiceFeature... features) {
        super(__getWsdlLocation(), MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_QNAME, features);
    }

    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCR(URL wsdlLocation) {
        super(wsdlLocation, MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_QNAME);
    }

    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCR(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_QNAME, features);
    }

    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCR(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCR(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap() {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap12")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap12() {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap12"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap12")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRSoap12"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpGet")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet() {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpGet"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpGet")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpGet"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpPost")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost() {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpPost"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost
     */
    @WebEndpoint(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpPost")
    public MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost getMóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("https://fundacionucr.ac.cr/", "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpPost"), MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_EXCEPTION!= null) {
            throw MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_EXCEPTION;
        }
        return MóDULOX0020SERVICIOSX0020EXTERNOSX0020X0028MSEX0029X0020X0020FUNDACIóNX0020UCR_WSDL_LOCATION;
    }

}
