
package com.icp.sigipro.webservices;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Mó3dulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundació3n_x0020_UCRSoap", targetNamespace = "https://fundacionucr.ac.cr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRSoap {


    /**
     * 
     * @param subtotalFactura
     * @param fechaExp
     * @param plazo
     * @param notas
     * @param proyecto
     * @param codigoOrden
     * @param nombreFactura
     * @param productosJson
     * @param totalFactura
     * @param llave
     * @param porcentajeDescuento
     * @param usuarioEjecuta
     * @param ccv
     * @param moneda
     * @param codUsuarioEjecuta
     * @param correoEnviar
     * @param tarjeta
     * @return
     *     returns com.icp.sigipro.webservices.FacturasWs
     */
    @WebMethod(operationName = "PagoLinea", action = "https://fundacionucr.ac.cr/PagoLinea")
    @WebResult(name = "PagoLineaResult", targetNamespace = "https://fundacionucr.ac.cr/")
    @RequestWrapper(localName = "PagoLinea", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.PagoLinea")
    @ResponseWrapper(localName = "PagoLineaResponse", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.PagoLineaResponse")
    public FacturasWs pagoLinea(
        @WebParam(name = "tarjeta", targetNamespace = "https://fundacionucr.ac.cr/")
        String tarjeta,
        @WebParam(name = "ccv", targetNamespace = "https://fundacionucr.ac.cr/")
        String ccv,
        @WebParam(name = "fechaExp", targetNamespace = "https://fundacionucr.ac.cr/")
        String fechaExp,
        @WebParam(name = "codigoOrden", targetNamespace = "https://fundacionucr.ac.cr/")
        int codigoOrden,
        @WebParam(name = "usuarioEjecuta", targetNamespace = "https://fundacionucr.ac.cr/")
        String usuarioEjecuta,
        @WebParam(name = "codUsuarioEjecuta", targetNamespace = "https://fundacionucr.ac.cr/")
        int codUsuarioEjecuta,
        @WebParam(name = "nombreFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        String nombreFactura,
        @WebParam(name = "proyecto", targetNamespace = "https://fundacionucr.ac.cr/")
        int proyecto,
        @WebParam(name = "moneda", targetNamespace = "https://fundacionucr.ac.cr/")
        int moneda,
        @WebParam(name = "plazo", targetNamespace = "https://fundacionucr.ac.cr/")
        int plazo,
        @WebParam(name = "porcentajeDescuento", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal porcentajeDescuento,
        @WebParam(name = "subtotalFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal subtotalFactura,
        @WebParam(name = "totalFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal totalFactura,
        @WebParam(name = "correoEnviar", targetNamespace = "https://fundacionucr.ac.cr/")
        String correoEnviar,
        @WebParam(name = "notas", targetNamespace = "https://fundacionucr.ac.cr/")
        String notas,
        @WebParam(name = "productosJson", targetNamespace = "https://fundacionucr.ac.cr/")
        String productosJson,
        @WebParam(name = "llave", targetNamespace = "https://fundacionucr.ac.cr/")
        String llave);

    /**
     * 
     * @param subtotalFactura
     * @param plazo
     * @param notas
     * @param proyecto
     * @param codigoOrden
     * @param nombreFactura
     * @param productosJson
     * @param totalFactura
     * @param llave
     * @param porcentajeDescuento
     * @param usuarioEjecuta
     * @param moneda
     * @param codUsuarioEjecuta
     * @param correoEnviar
     * @return
     *     returns com.icp.sigipro.webservices.FacturasWs
     */
    @WebMethod(operationName = "LineasProductos", action = "https://fundacionucr.ac.cr/LineasProductos")
    @WebResult(name = "LineasProductosResult", targetNamespace = "https://fundacionucr.ac.cr/")
    @RequestWrapper(localName = "LineasProductos", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.LineasProductos")
    @ResponseWrapper(localName = "LineasProductosResponse", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.LineasProductosResponse")
    public FacturasWs lineasProductos(
        @WebParam(name = "codigoOrden", targetNamespace = "https://fundacionucr.ac.cr/")
        int codigoOrden,
        @WebParam(name = "usuarioEjecuta", targetNamespace = "https://fundacionucr.ac.cr/")
        String usuarioEjecuta,
        @WebParam(name = "codUsuarioEjecuta", targetNamespace = "https://fundacionucr.ac.cr/")
        int codUsuarioEjecuta,
        @WebParam(name = "nombreFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        String nombreFactura,
        @WebParam(name = "proyecto", targetNamespace = "https://fundacionucr.ac.cr/")
        int proyecto,
        @WebParam(name = "moneda", targetNamespace = "https://fundacionucr.ac.cr/")
        int moneda,
        @WebParam(name = "plazo", targetNamespace = "https://fundacionucr.ac.cr/")
        int plazo,
        @WebParam(name = "porcentajeDescuento", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal porcentajeDescuento,
        @WebParam(name = "subtotalFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal subtotalFactura,
        @WebParam(name = "totalFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal totalFactura,
        @WebParam(name = "correoEnviar", targetNamespace = "https://fundacionucr.ac.cr/")
        String correoEnviar,
        @WebParam(name = "notas", targetNamespace = "https://fundacionucr.ac.cr/")
        String notas,
        @WebParam(name = "productosJson", targetNamespace = "https://fundacionucr.ac.cr/")
        String productosJson,
        @WebParam(name = "llave", targetNamespace = "https://fundacionucr.ac.cr/")
        String llave);

    /**
     * 
     * @param subtotalFactura
     * @param plazo
     * @param notas
     * @param proyecto
     * @param codigoOrden
     * @param nombreFactura
     * @param detalle
     * @param totalFactura
     * @param llave
     * @param porcentajeDescuento
     * @param usuarioEjecuta
     * @param moneda
     * @param codUsuarioEjecuta
     * @param correoEnviar
     * @return
     *     returns com.icp.sigipro.webservices.FacturasWs
     */
    @WebMethod(operationName = "DetalleServicio", action = "https://fundacionucr.ac.cr/DetalleServicio")
    @WebResult(name = "DetalleServicioResult", targetNamespace = "https://fundacionucr.ac.cr/")
    @RequestWrapper(localName = "DetalleServicio", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.DetalleServicio")
    @ResponseWrapper(localName = "DetalleServicioResponse", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.DetalleServicioResponse")
    public FacturasWs detalleServicio(
        @WebParam(name = "codigoOrden", targetNamespace = "https://fundacionucr.ac.cr/")
        int codigoOrden,
        @WebParam(name = "usuarioEjecuta", targetNamespace = "https://fundacionucr.ac.cr/")
        String usuarioEjecuta,
        @WebParam(name = "codUsuarioEjecuta", targetNamespace = "https://fundacionucr.ac.cr/")
        int codUsuarioEjecuta,
        @WebParam(name = "nombreFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        String nombreFactura,
        @WebParam(name = "proyecto", targetNamespace = "https://fundacionucr.ac.cr/")
        int proyecto,
        @WebParam(name = "moneda", targetNamespace = "https://fundacionucr.ac.cr/")
        int moneda,
        @WebParam(name = "plazo", targetNamespace = "https://fundacionucr.ac.cr/")
        int plazo,
        @WebParam(name = "porcentajeDescuento", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal porcentajeDescuento,
        @WebParam(name = "subtotalFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal subtotalFactura,
        @WebParam(name = "totalFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        BigDecimal totalFactura,
        @WebParam(name = "correoEnviar", targetNamespace = "https://fundacionucr.ac.cr/")
        String correoEnviar,
        @WebParam(name = "notas", targetNamespace = "https://fundacionucr.ac.cr/")
        String notas,
        @WebParam(name = "detalle", targetNamespace = "https://fundacionucr.ac.cr/")
        String detalle,
        @WebParam(name = "llave", targetNamespace = "https://fundacionucr.ac.cr/")
        String llave);

    /**
     * 
     * @param proyecto
     * @param numeroFactura
     * @return
     *     returns com.icp.sigipro.webservices.FacturasPagosWs
     */
    @WebMethod(operationName = "EstadoFactura", action = "https://fundacionucr.ac.cr/EstadoFactura")
    @WebResult(name = "EstadoFacturaResult", targetNamespace = "https://fundacionucr.ac.cr/")
    @RequestWrapper(localName = "EstadoFactura", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.EstadoFactura")
    @ResponseWrapper(localName = "EstadoFacturaResponse", targetNamespace = "https://fundacionucr.ac.cr/", className = "com.icp.sigipro.webservices.EstadoFacturaResponse")
    public FacturasPagosWs estadoFactura(
        @WebParam(name = "numeroFactura", targetNamespace = "https://fundacionucr.ac.cr/")
        int numeroFactura,
        @WebParam(name = "proyecto", targetNamespace = "https://fundacionucr.ac.cr/")
        int proyecto);

}
