
package com.icp.sigipro.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Módulo_x0020_Servicios_x0020_Externos_x0020__x0028_MSE_x0029__x0020_-_x0020_Fundación_x0020_UCRHttpGet", targetNamespace = "https://fundacionucr.ac.cr/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MóduloX0020ServiciosX0020ExternosX0020X0028MSEX0029X0020X0020FundaciónX0020UCRHttpGet {


    /**
     * 
     * @param subtotalFactura
     * @param fechaExp
     * @param plazo
     * @param notas
     * @param proyecto
     * @param codigoOrden
     * @param nombreFactura
     * @param productosJson
     * @param totalFactura
     * @param llave
     * @param porcentajeDescuento
     * @param usuarioEjecuta
     * @param ccv
     * @param moneda
     * @param codUsuarioEjecuta
     * @param correoEnviar
     * @param tarjeta
     * @return
     *     returns com.icp.sigipro.webservices.FacturasWs
     */
    @WebMethod(operationName = "PagoLinea")
    @WebResult(name = "FacturasWs", targetNamespace = "https://fundacionucr.ac.cr/", partName = "Body")
    public FacturasWs pagoLinea(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "tarjeta")
        String tarjeta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ccv")
        String ccv,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fechaExp")
        String fechaExp,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "codigoOrden")
        String codigoOrden,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuarioEjecuta")
        String usuarioEjecuta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "codUsuarioEjecuta")
        String codUsuarioEjecuta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nombreFactura")
        String nombreFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "proyecto")
        String proyecto,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "moneda")
        String moneda,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "plazo")
        String plazo,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "porcentajeDescuento")
        String porcentajeDescuento,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "subtotalFactura")
        String subtotalFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "totalFactura")
        String totalFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "correoEnviar")
        String correoEnviar,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "notas")
        String notas,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "productosJson")
        String productosJson,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "llave")
        String llave);

    /**
     * 
     * @param subtotalFactura
     * @param plazo
     * @param notas
     * @param proyecto
     * @param codigoOrden
     * @param nombreFactura
     * @param productosJson
     * @param totalFactura
     * @param llave
     * @param porcentajeDescuento
     * @param usuarioEjecuta
     * @param moneda
     * @param codUsuarioEjecuta
     * @param correoEnviar
     * @return
     *     returns com.icp.sigipro.webservices.FacturasWs
     */
    @WebMethod(operationName = "LineasProductos")
    @WebResult(name = "FacturasWs", targetNamespace = "https://fundacionucr.ac.cr/", partName = "Body")
    public FacturasWs lineasProductos(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "codigoOrden")
        String codigoOrden,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuarioEjecuta")
        String usuarioEjecuta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "codUsuarioEjecuta")
        String codUsuarioEjecuta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nombreFactura")
        String nombreFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "proyecto")
        String proyecto,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "moneda")
        String moneda,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "plazo")
        String plazo,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "porcentajeDescuento")
        String porcentajeDescuento,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "subtotalFactura")
        String subtotalFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "totalFactura")
        String totalFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "correoEnviar")
        String correoEnviar,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "notas")
        String notas,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "productosJson")
        String productosJson,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "llave")
        String llave);

    /**
     * 
     * @param subtotalFactura
     * @param plazo
     * @param notas
     * @param proyecto
     * @param codigoOrden
     * @param nombreFactura
     * @param detalle
     * @param totalFactura
     * @param llave
     * @param porcentajeDescuento
     * @param usuarioEjecuta
     * @param moneda
     * @param codUsuarioEjecuta
     * @param correoEnviar
     * @return
     *     returns com.icp.sigipro.webservices.FacturasWs
     */
    @WebMethod(operationName = "DetalleServicio")
    @WebResult(name = "FacturasWs", targetNamespace = "https://fundacionucr.ac.cr/", partName = "Body")
    public FacturasWs detalleServicio(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "codigoOrden")
        String codigoOrden,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuarioEjecuta")
        String usuarioEjecuta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "codUsuarioEjecuta")
        String codUsuarioEjecuta,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nombreFactura")
        String nombreFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "proyecto")
        String proyecto,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "moneda")
        String moneda,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "plazo")
        String plazo,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "porcentajeDescuento")
        String porcentajeDescuento,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "subtotalFactura")
        String subtotalFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "totalFactura")
        String totalFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "correoEnviar")
        String correoEnviar,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "notas")
        String notas,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "detalle")
        String detalle,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "llave")
        String llave);

    /**
     * 
     * @param proyecto
     * @param numeroFactura
     * @return
     *     returns com.icp.sigipro.webservices.FacturasPagosWs
     */
    @WebMethod(operationName = "EstadoFactura")
    @WebResult(name = "FacturasPagosWs", targetNamespace = "https://fundacionucr.ac.cr/", partName = "Body")
    public FacturasPagosWs estadoFactura(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numeroFactura")
        String numeroFactura,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "proyecto")
        String proyecto);

}
