INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 18x1','AH-1825','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 18x1 1/2 ','AH-1838','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 20x1 ','AH-2025','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 20x1 1/2 ','AH-2038','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 21x 1 ','AH-2125','BD-BECTON DICKINSON',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodermica 21x1 1/2 ','AH-2138','VACUTAINER',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 22x1 1/2 ','','RYMCO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 22x1 1/2 ','','BD-BECTON DICKINSON',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 23x1 ','','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 23x1 ','','BD-BECTON DICKINSON',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 25x1 ','AH-2525','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 25x1 1/2 ','AH-2540','BRAUN/NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 25x5/8 ','AH-2516','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 26x1/2 ','AH-2613','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 27x1/2 ','AH-2713','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aguja hipodérmica 30x1/2 ','AH-3013','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Anillo Retenedor','SC138150','MEDITEK',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Anillos para histología','M460','SIMPORT',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aplicador de madera sin algodón ','14-960-3S','FISHERBRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Aplicadores de madera con algodón','14-960-3G','FAPACO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Asas esteriles desechables',' 22-363-600','Fisher',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bateria AA','AA48964','RAYOVAC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bateria AAA','AAA47856','RAYOVAC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bateria para reloj','626','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Baterias CR2032 (suavizador agua producción)','CR2032','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bolsas de Bioseguridad 24x36','1312-2436','FISHER BRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bolsas de Bioseguridad 37x48','1312-3748','FISHER BRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bolsas de Bioseguridad Pequeñas 19x23','01-828C ','FISHER BRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bolsas de Bioseguridad Pequeñas 8x12','01-828A','FISHER BRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bolsas Ziploc Medianas','','ZIPLOC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bolsas Ziploc Pequeñas','','ZIPLOC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Botellas 150cm² p/ cultivo celular ','F430825','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Botellas 225cm² p/ cultivo celular ','F3000','COSTAR',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Botellas 175cm² p/ cultivo celular ','cls3292','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Botellas 75cm² p/ cultivo celular ','cls430641','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer ph 10 500 ml','4120L66','BOECO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer pH 10 (Caja)','4120L66','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer ph 4 (sobre)','','Thermo',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer ph 4 (botella)','4120L55','BOECO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer pH 4 (caja)','4120L55','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer ph 7 (sobre)','','Thermo',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer ph 7 (botella)','4120L60','BOECO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer pH 7 (caja)','4120L60','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Buffer rinse ','4120L70','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Bulbos (tapones de hule)','14-065B','BRANSTEAD',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Caja de pañuelos Kleenex','K154105','KLEENEX',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cajitas cryo almacenamiento de alto impacto','T314-281B','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Canaletas esteriles individual','07-200-127  ','FISHER SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Canaletas esteriles por paquete','','FISHER SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Canaletas no esteriles ','13-681-500','FISHER SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cartucho contra vapores y gases múltiples','6006','3M',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cassette para histología cuadrados','M499-2 ','SIMPORT',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cassette para histología redondos','15-182-218','FISHER SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cepillo de acero con mango','C02728','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cilindro de gas 1,02 libras','CG5103','Coleman',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Crioviales 2ml','5000-0020 ','NALGENE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cuchillas para micrótomo mx35','mx35 3051835','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Cuchillas para micrótomo mx35','mx35 3051835','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Eppendorf  2ml','IB-623201','Greiner bio-one',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Eppendorf 0,5','P11-259','EPPENDORF',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Eppendorf combitips Advanced 50ml','30089-48','EPPENDORF',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Escobillas','E01627','ETERNA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Esponja corriente scotch brite','E1352','SCOTCH BRITE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Esponja doble uso scotch brite','E2423','SCOTCH BRITE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Etiquetas adhesivas blancas (rollos 1200 unidades)','R-30','ETIPLAST',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Etiquetas adhesivas blancas (rollos 2500 unidades)','R-12','ETIPLAST',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Etiquetas adhesivas blancas (rollos 8000 unidades)','R-39','ETIPLAST',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Equipo de filtracion','09-753-1C','FisherBrand',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro 1um PALL','NP6U0112P1G','Pall',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro contra particulas 3m rosado','F07184','3M',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro de membrana MF recuento microbiano','HAWG04756','MILLIPORE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro desechable con indicador','SC1361','STERIS CORPORATION',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro HEPA Envirco cámara flujo laminar grande 99.99%','SN162002','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro HEPA Envirco cámara flujo laminar mediana 99.99%','SN169919','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro para jeringa 5 micras 32mm','4662','PALL',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro Sartopure PP2 5µm','','SARTORIUS',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro Sartopure PP2 50µm','','SARTORIUS',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro Sealkleen 0,22µm','SLK7002NFZP','PALL',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro Z-Carbon Cuno','','3M',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtro Z-Plus Cuno','','3M',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 0,20µ 10” Dominic Hunter','ZCMT1/020E-A','DOMINIC HUNTER',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 0,20µ 10” Liquatec','AR0020S01A','LIQUATEC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 0,22 µm 10” Flow Max HP','FPP-O,2-10-222','FLOW-MAX-HP',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 0,2 µm para carcaza','AB1NFZ7PH4','PALL',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 2 µm para carcaza','Ab2U2-20Z-7H4','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 0.22 µm para carcaza','AB2NFZ7PH4','PALL',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 0.22 µm Bioassure grado esterilizante no cargados','PDA020F02BA','CUNO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 10” cartucho carbón activado Filterite','C10P-A','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros 8-20 µ Supracap 100 para Taiwan','NP8P9001','PALL',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 1/4 IN  ','F740-E','Schleider & Schuell',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 110mm, 20-25 poro um, veloc 65 s/100ml ','F411','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 110mm, 7-11 poro um, veloc 261 s/100mL','F502','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 110mm, 7-11 poro um, veloc 358 s/100ml ','F413','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 125mm (#41) ','F1441-125','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 150mm (#5) ','F1005-150','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 150mm (2v)  ','F1202-150','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 24cm (#54)','F1454-240','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros de papel 90mm (#3) ','F1003-090','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros HEPA 24x48x3 99.99% eficiencia túnel flujo laminar separación plasma','P5-24.00-4800','HEPA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros membrana para ultrafiltrador','CDUF 050 TI','MILLIPORE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros ópticos 4” 0,20µ PALL ','KA2PFRP 1','PALL',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros ópticos 4” Millipore  0,22 µ','KVGB04TC 3','MILLIPORE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros p/ jeringas plásticos 0.2um (hidrofilico) estériles ','','MINISART',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros p/ jeringas plásticos 0.2um (hidrofilico) estériles ','','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros p/jeringas plásticos 0.45um (hidrofilico) SFCA estériles','F17829','MINISARY',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros contra partículas ','F5N11-N95','3M',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Filtros retentivos whatmann de 50 cm ','','WHATMAN',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Gasa de acero inoxidable 2" 13mhhm-7','G119-30','COLE-PARMER',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Gradillas Supelco','cat.23201','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de goma neopreno talla 8','','PROTEK',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex "XS"','AJ200XS','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex M libres de polvo (proteómica)','19-050-548B','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex S libre de polvo (proteómica)','19-050-548A','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex talla "L"','AJ200L','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex talla "M"','','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex talla "M"','','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex talla "M"','','HEALTH',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex talla"S"','','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de latex talla"S"','','AMBIDERM',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de Neopreno Azul','G256-099','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de nitrilo L','','NBR',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de nitrilo M','AJ075','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de nitrilo S','','NBR',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de nitrilo S','','SAFINA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de nylón','G11-393-1B','FISHER-SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de plástico trans.polietileno M 11-394','G11-394M','FISHERBRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes de plástico trans.polietileno S 11-394','G11-394-S','FISHERBRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes estériles #7½ ','G500394','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes profesional G40 talla 10 "XL"','','Kimberly-Clark',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes profesional G80 talla 8 "M" (verdes)','','Kimberly-Clark',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes profesional G80 talla 9 "L" (verdes)','','Kimberly-Clark',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Guantes quirurjicos T7 esteriles ','','SURGICAL GLOVES',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Hojas de bisturies #10 ','','SURGICAL BLAVES',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Hojas de bisturies #11 ','','SURGICAL BLAVES',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Hojas de bisturies #15 ','','SURGICAL BLAVES',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Hojas de bisturies #22 ','','SURGICAL BLAVES',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Hojas graficador Dickson para 7 días con temp. y humedad','H80013-13','DICKSON',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Indicador Biologico','','3M',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa  20ml con aguja ','JD-20L2130-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa  50ml sin aguja ','JD-50L-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 10ml con aguja 21x1 1/2','JD-10L2138-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 10ml sin aguja ','JD-10L-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 1ml con aguja 27 G x 1/2','JD-01U2713','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 1ml de tuberculina 27x1/2 ','JD-01T2713-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 20ml sin aguja ','JD-20L-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 30 ml sin aguja ','JD-30L-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 3ml con aguja 21x1 1/2 ','JD-03L2138','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 3ml sin aguja','','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 50ml sin aguja Irrigación','JD-50C','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 5ml con aguja  22X1 1/2','JD-05L2238-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa 5ml sin aguja ','JD-05L-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa de vidrio 10 cc','449169','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa estériles 60 ml sin aguja ','JD-60L-SB','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Jeringa plásticas descartable 0.5ml con aguja ','JD-0.5L','BD ULTRA-FINE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Lancetas','','BD-MICROLANCED',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Llaves de paso para jeringa','31507-10','COLE-PARMER',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Mascarillas desechables cónicas  ','','AMBIDERM',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Mascarillas desechables quirúrgicas alargadas','M12117','VIAMED',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Masking Tape 1/2 blanco','','SCOTCH',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Membrana Osmosis Reversa Rilmtec Elemento LOTFC 4x40 xle-4040','M80202','FILMTEC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('micro columnas','69725','Thermo scientific',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Microplacas 96 V 0,25ml ','P6908C03','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Mopas de 24"','DM-23524WB','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Paños para tareas delicadas (KIMWIPES)','','Kimberly-Clark',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Papel Aluminio','P100328','DIAPACK',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Papel para pesar cuadrado 3x3 ','P09-898-12A','FISHER BRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Papel para pesar cuadrado 4x4 ','P09-898-12B','FISHER BRAND',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Papel Parafilm','PM-996','PARAFILM',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Papel toalla corriente','P147947','SCOTT',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Papel toalla para dispensador 6x1x305 marca Scott','P53291','SCOTT',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Pera de silicona color rojo para llenar pipetas','P7775F07','THOMAS SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Pipetas de transferencia (plásticas) esteriles','Z13,507-0','Sigma',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Pipetas estériles 10ml','CLS4488','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Pipetas estériles 2ml 4021','','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Pipetas estériles 50ml','CLS4490','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Pipetas estériles 5ml ','CLS4487','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas 96 para cultivo esteriles fondo U','CLS3790','Sigma',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas cultivo celular 24 hoyos estéril','CLS3526','SIGMA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas cultivo celular 6 hoyos estéril','CLS3516','SIGMA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas cultivo celular 96 hoyos estéril','cls3595','SIGMA',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas de agar contacto biotest TC-931050','TC-931050','BIOTEST',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas de Elisa media unión','PP9017','COSTAR',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas de Elisa alta unión','PP9018','COSTAR',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas de Elisa esteriles','PP3370','COSTAR',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas de Elisa fondo plano no esteriles','','FISHER SCIENTIFIC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas de Elisa fondo plano para cultivo esteriles ','M-9780','Sigma',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas de gelatina ','','EDU',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas Filtrantes','K900P','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas Petri 100mm x 15mm','P5731','SIGMA-ALDRICH',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas Petri 100mm x 20mm','P5606','SIGMA-ALDRICH',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas Petri 150mm x 15mm','P5981','SIGMA-ALDRICH',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Placas petri para recuento microbiano (medio de cultivo)','','SARTORIUS',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Plástico para envolver cajas exportación','','ETIPLAST',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Plástico termoencogible 12”x600 m doble (en rollos)','P0709-164','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Prefiltros ductos aire Airguard 24x24x2 class 2 453N','DP40-205-02','AIRGUARD',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Prefiltros ductos aire Clarcor Airguard 24x24x4','DP40-STD4','AIRGUARD',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Prefiltros Osmosis Reversa (viejo) Betapure 5 µ','AU20B11NN','LIQUATEC',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Prefiltros Osmosis Reversa Pentek 5 micras nominal','P5-20','PENTEK',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Prefiltros Osmosis Reversa Pentek 5 micras nominal','SDC-25-2005','Hydronix',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Pre-filtros ultrafiltrador  Hydronix 5 µ','SDF-25-1005','HIDRONIX',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas 10uL (libre de ARNasas,ADNasas,Pirógenos,ADN)','','NEPTUNE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas 200ul para cargar geles','02-707-181','FisherBrand',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas 200ul para cargar geles caja azul','3692-11','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas p´ pipeta estériles 50-1000 ml (5x96 c/u)','P7732C97','EPPENDORF',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas p´pipeta estériles 100-5000 ml (5x100c/u)','','EPPENDORF',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas p´pipeta 1-10 ul','','EPPENDORF',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas p´pipeta estériles 1-20 ul (5x96c/u)','','EPPENDORF',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Puntas para pipeta 10ml','','EPPENDORF',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Retapadora Manual ','W225303','Wheaton ',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Retenedor de filtro lateral 3M','','3M',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tapas PCR color','CLS3743','Sigma',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tapas PCR transparentes','CLS3743','Sigma',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tape empaque transparente 2”x 91 m','','ETIPLAST',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tapones para ACLQ color rojo (unidades)','V9025','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tapones para POLF color gris','V9355','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tapones para POLQ color gris','V9025','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tarjeta de datos con indicador','SC1387','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tijera acero inoxidable','AM-1497','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubo Microcentrifug O-ring 2ml ','T334-6S','SIMPORT',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubo tapa lila con EDTA K2 6ml','456043','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubo tapa lila con EDTA K3 4ml','454021','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubos  cónicos para Centrifuga 50ml  (racks)','CLS430290','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubos cónicos  para Centrifuga 15ml (bolsa)','LB-188271','',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubos cónicos  para Centrifuga 50ml (bolsa)','LB-227261','Greiner bio-one',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubos cónicos de ultrafiltración 2ml','','Fisher Scientific',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubos cónicos para Centrifuga 15ml (paquete)','CLS430052','CORNING',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubos cónicos para Centrifuga 50ml (paquete)','','Evergreen',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Tubos tapa roja 9ml sin gel','455092','NIPRO',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Unidades de filtración para centrifuga ','UF4305','MILLIPORE',Null);
INSERT INTO bodega.catalogo_externo (producto, codigo_externo, marca, id_proveedor) VALUES ('Viales borosilicato tipo I 10 ml Liquidos cajas 165 unidades ','DIN58336','THURINGER',Null);

UPDATE bodega.catalogo_externo SET codigo_externo='No tiene codigo externo' where codigo_externo= '';
UPDATE bodega.catalogo_externo SET marca='No tiene codigo externo' where marca= ''; 

