CREATE TABLE CABALLERIZA.IMAGENES(
	ID_IMAGEN serial NOT NULL,
	ID_CABALLO integer NOT NULL,
	IMAGEN bytea
);

ALTER TABLE ONLY CABALLERIZA.IMAGENES ADD CONSTRAINT PK_IMAGENES PRIMARY KEY (ID_IMAGEN);
ALTER TABLE ONLY CABALLERIZA.IMAGENES ADD CONSTRAINT FK_ID_CABALLO FOREIGN KEY (ID_CABALLO) REFERENCES CABALLERIZA.CABALLOS(ID_CABALLO);

ALTER TABLE CABALLERIZA.CABALLOS
DROP COLUMN FOTOGRAFIA;

