ALTER TABLE SERPENTARIO.EVENTOS
ALTER COLUMN OBSERVACIONES TYPE character varying (2000);

ALTER TABLE serpentario.extraccion
ADD COLUMN "interno" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE serpentario.lote
ADD COLUMN "interno" BOOLEAN NOT NULL DEFAULT TRUE;