ALTER TABLE CONTROL_CALIDAD.ANALISIS
    ADD COLUMN ESTADO CHARACTER VARYING(50);

UPDATE CONTROL_CALIDAD.ANALISIS
SET ESTADO = 'Aprobado'
WHERE APROBADO = true;

UPDATE CONTROL_CALIDAD.ANALISIS
SET ESTADO = 'Pendiente'
WHERE APROBADO = false;

ALTER TABLE CONTROL_CALIDAD.ANALISIS
    DROP COLUMN APROBADO;

UPDATE SEGURIDAD.PERMISOS SET NOMBRE = '[ControlCalidad]Aprobar/Retirar Análisis' WHERE id_permiso = 544;