/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Luis Diego
 * Created: Oct 8, 2016
 */

ALTER TABLE PRODUCCION.HISTORIAL_ACTIVIDAD_APOYO
ALTER COLUMN REQUIERE_COORDINACION type BOOLEAN;

ALTER TABLE PRODUCCION.HISTORIAL_ACTIVIDAD_APOYO
ALTER COLUMN REQUIERE_REGENCIA type BOOLEAN;

ALTER TABLE PRODUCCION.RESPUESTA_AA
ALTER COLUMN APROBACION_COORDINACION type BOOLEAN;

ALTER TABLE PRODUCCION.RESPUESTA_AA
ALTER COLUMN APROBACION_REGENCIA type BOOLEAN;

ALTER TABLE PRODUCCION.HISTORIAL_RESPUESTA_AA
RENAME COLUMN id_usuario_aprobar to id_usuario_aprobar_coordinacion;

ALTER TABLE PRODUCCION.HISTORIAL_RESPUESTA_AA
RENAME COLUMN id_usuario_revisar to id_usuario_cerrar;

ALTER TABLE PRODUCCION.HISTORIAL_RESPUESTA_AA
ADD COLUMN ID_USUARIO_APROBAR_REGENCIA INT;

ALTER TABLE ONLY PRODUCCION.HISTORIAL_RESPUESTA_AA ADD CONSTRAINT FK_ID_USUARIO_APROBAR_REGENCIA FOREIGN KEY (ID_USUARIO_APROBAR_REGENCIA) REFERENCES SEGURIDAD.USUARIOS(ID_USUARIO);