ALTER TABLE SERPENTARIO.SERPIENTES
ADD COLUMN NUMERO_SERPIENTE integer NOT NULL UNIQUE;

CREATE UNIQUE INDEX i_numero_serpiente ON serpentario.serpientes USING btree (numero_serpiente);

ALTER TABLE SERPENTARIO.LOTE
ADD COLUMN NUMERO_LOTE CHARACTER VARYING(10) NOT NULL UNIQUE;

ALTER TABLE SERPENTARIO.COLECCION_HUMEDA
ADD COLUMN NUMERO_COLECCION_HUMEDA integer NOT NULL UNIQUE;

ALTER TABLE SERPENTARIO.CATALOGO_TEJIDO
ADD COLUMN NUMERO_CATALOGO_TEJIDO integer NOT NULL UNIQUE;
